% Klasa dokumentów do składu prac dyplomowych na Wydziale Matematyki
% i Informatyki UWM.
%
% Na podstawie:
% http://www.latex-project.org/guides/clsguide.pdf

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{wmiibook}[2012/04/26 v0.2 Praca dyplomowa WMiI]

%deklaracja klasy bazowej, możliwość przekazywania opcji z klasy bazowej

% ------------------------------------------------------------------------------
%\DeclareOption*{\PassOptionsToClass{\CurrentOption}{report}}
%\ProcessOptions\relax
%\LoadClass{report}
% ------------------------------------------------------------------------------
\LoadClassWithOptions{report}
